import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

shell = "/opt/homebrew/bin/fish"

[window]
startup_mode = "Maximized"

[font]
normal = { family = "Cascadia Code NF", style = "SemiLight" }
bold = { family = "Cascadia Code NF", style = "SemiBold" }
italic = { family = "Cascadia Code NF", style = "SemiLight Italic" }
bold_italic = { family = "Cascadia Code NF", style = "SemiBold Italic" }
size = 16
offset = { y = 2 }

